// Generated by CoffeeScript 1.10.0
(function() {
  var BINDIR, DATADIR, DESTNAME, ID, NAME, SOURCENAME, fs, path;

  fs = require('fs.extra');

  path = require('path');

  NAME = 'Palomino';

  ID = 'com.rockiger.palomino';

  BINDIR = '/usr/bin';

  DATADIR = '/usr/share';

  SOURCENAME = './bin/palomino';

  DESTNAME = 'palomino';

  fs.copy(SOURCENAME, path.join(BINDIR, DESTNAME), {
    replace: true
  }, function(err) {
    if (err != null) {
      throw err;
    }
    fs.chmodSync(path.join(BINDIR, DESTNAME), 0x1ed);
    return console.log("Copied binary");
  });

  fs.copy('./src/desktop', path.join(DATADIR, 'applications', ID + '.desktop'), {
    replace: true
  }, function(err) {
    if (err != null) {
      throw err;
    }
    return console.log("Copied desktop file");
  });

  fs.copy('./src/dbus.service', path.join(DATADIR, 'dbus-1/services', ID + '.service'), {
    replace: true
  }, function(err) {
    if (err != null) {
      throw err;
    }
    return console.log("Copied service file");
  });

}).call(this);
