// Generated by CoffeeScript 1.10.0
(function() {
  var Gdk, Gio, Glib, Gtk, Lang, NewMailWindow, Palomino, SPACING, Webkit, app;

  Gtk = imports.gi.Gtk;

  Lang = imports.lang;

  Webkit = imports.gi.WebKit2;

  Glib = imports.gi.GLib;

  Gdk = imports.gi.Gdk;

  Gio = imports.gi.Gio;

  SPACING = 10;

  NewMailWindow = new Lang.Class({
    Name: 'NewMailWindow',
    _init: function(webview) {
      return this._buildWindow(webview);
    },
    _buildWindow: function(webview) {
      this._window = new Gtk.Window({
        title: 'Write E-Mail',
        default_width: 850,
        default_height: 700,
        window_position: Gtk.WindowPosition.CENTER
      });
      this._vBox = new Gtk.Box({
        orientation: Gtk.Orientation.VERTICAL,
        spacing: SPACING
      });
      this._webview = webview;
      this._mousetarget = new Webkit.HitTestResult();
      this._headerbar = new Gtk.HeaderBar();
      this._headerbar.set_title("Write Mail");
      this._headerbar.set_show_close_button(true);
      this._window.set_titlebar(this._headerbar);
      this._window.add(this._webview);
      return this._window.show_all();
    },
    onReadyToShow: function() {
      return print('onReadyToShow');
    }
  });

  Palomino = new Lang.Class({
    Name: 'Palomino',
    _init: function() {
      this.application = new Gtk.Application({
        application_id: 'com.rockiger.palomino'
      });
      this._buildActions();
      this.application.connect('activate', Lang.bind(this, this._onActivate));
      this.application.connect('startup', Lang.bind(this, this._onStartup));
      return this.application.connect('shutdown', Lang.bind(this, this._onShutdown));
    },
    _onActivate: function() {
      return this._window.present();
    },
    _onStartup: function() {
      return this._buildUI();
    },
    _onShutdown: function() {
      return print("Shutdown");
    },
    _buildUI: function() {
      this._window = new Gtk.Window({
        application: this.application,
        title: 'Palomino',
        default_width: 1600,
        default_height: 900,
        window_position: Gtk.WindowPosition.CENTER
      });
      this._vBox = new Gtk.Box({
        orientation: Gtk.Orientation.VERTICAL,
        spacing: SPACING
      });
      this._webview = new Webkit.WebView();
      this._mousetarget = new Webkit.HitTestResult();
      this._headerbar = new Gtk.HeaderBar();
      this._headerbar.set_title("Palomino");
      this._headerbar.set_show_close_button(true);
      this._window.set_titlebar(this._headerbar);
      this._newMessageButton = new Gtk.Button();
      this._newMessageIcon = new Gio.ThemedIcon({
        name: "list-add-symbolic"
      });
      this._newMessageImage = new Gtk.Image({
        gicon: this._newMessageIcon
      });
      this._newMessageButton.add(this._newMessageImage);
      this._settingsButton = new Gtk.Button();
      this._settingsIcon = new Gio.ThemedIcon({
        name: "preferences-system-symbolic"
      });
      this._settingsImage = new Gtk.Image({
        gicon: this._settingsIcon
      });
      this._settingsButton.add(this._settingsImage);
      this._headerbar.pack_end(this._settingsButton);
      this._headerbar.pack_start(this._newMessageButton);
      this._revealer = new Gtk.Revealer();
      this._revealer.set_transition_duration(1000);
      this._revealer.set_transition_type(Gtk.RevealerTransitionType.SLIDE_LEFT);
      this._message = new Gtk.Label();
      this._msgState = this._message.get_state();
      this._msgBgColor = new Gdk.RGBA();
      this._msgBgColor.parse("#f9edbe");
      this._message.override_background_color(this._msgState, this._msgBgColor);
      this._message.set_padding(10, 0);
      this._revealer.add(this._message);
      this._headerbar.pack_end(this._revealer);
      this._webcontext = this._webview.web_context;
      this._webcontext.set_cache_model(Webkit.CacheModel.DOCUMENT_VIEWER);
      this._cookie_manager = this._webcontext.get_cookie_manager();
      this._cookie_manager.set_persistent_storage('/home/macco/.palomino_cookies.txt', Webkit.CookiePersistentStorage.TEXT);
      this._websettings = this._webview.get_settings();
      this._websettings.set_javascript_can_open_windows_automatically(true);
      this._websettings.set_allow_modal_dialogs(true);
      this._websettings.set_enable_developer_extras(true);
      this._websettings.set_enable_smooth_scrolling(true);
      this._webview.load_uri('https://mail.google.com', null);
      this._window.add(this._webview);
      this._newMessageButton.connect('clicked', Lang.bind(this, this._onClickNewMessageBtn));
      this._webview.connect('show-notification', Lang.bind(this, this._onShowNotification));
      this._webview.connect('decide-policy', Lang.bind(this, this._onDecidePolicy));
      this._webview.connect('create', Lang.bind(this, this._onCreate));
      this._webview.connect('script-dialog', Lang.bind(this, this._onScriptDialog));
      this._webview.connect('mouse-target-changed', Lang.bind(this, this._onMouseTargetChanged));
      this._webcontext.connect('download-started', Lang.bind(this, this._onDownloadStarted));
      this._window.connect('key-press-event', Lang.bind(this, this._onKeyPress));
      return this._window.show_all();
    },
    _buildActions: function() {
      var newMailAction;
      print('_buildActions');
      newMailAction = new Gio.SimpleAction({
        name: 'new-mail'
      });
      newMailAction.connect('activate', Lang.bind(this, this._onNewMail));
      return this.application.add_action(newMailAction);
    },
    _onShowNotification: function() {
      return print('show-notification');
    },
    _onDecidePolicy: function(webview, policyDecision, policyDecisionType) {
      if (policyDecisionType === Webkit.PolicyDecisionType.NEW_WINDOW_ACTION) {
        print('NEW_WINDOW_ACTION');
        Gtk.show_uri(null, policyDecision.get_request().get_uri(), Gdk.CURRENT_TIME);
      }
      return false;
    },
    _onCreate: function(webview, navAction, window) {
      var TS, newWebview, newWindow, uri;
      print('on-create');
      uri = navAction.get_request().get_uri();

      /*
      Test if Googlemail want's  to open a new compose window
      if not open url in default browser
       */
      TS = "https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=";
      if ((uri != null) && uri.slice(0, TS.length) === TS) {
        newWebview = new Webkit.WebView({
          related_view: webview
        });
        newWebview.set_settings(webview.get_settings());
        newWindow = new NewMailWindow(newWebview);
        newWebview.connect('ready-to-show', Lang.bind(this, newWindow.onReadyToShow));
        newWebview.connect('close', Lang.bind(this, function() {
          return newWindow._window.destroy();
        }));
        return newWebview;
      } else {
        Gtk.show_uri(null, uri, 0);
        return null;
      }
    },
    _onScriptDialog: function(webview, dialog) {
      print('script-dialog');
      if (dialog.get_dialog_type() === Webkit.ScriptDialogType.ALERT && this._mousetarget.context_is_link()) {
        Gtk.show_uri(null, this._mousetarget.get_link_uri(), Gdk.CURRENT_TIME);
        return true;
      }
      return true;
    },
    _onMouseTargetChanged: function(webview, hitTestResult) {
      if (hitTestResult.context_is_link()) {
        print(hitTestResult.get_link_uri());
        this._mousetarget = hitTestResult;
      }
      return this._mousetarget;
    },
    _onClickNewMessageBtn: function() {
      print('onClickNewMessageBtn');
      return this._onNewMail();
    },
    _onDownloadStarted: function(webcontext, download) {
      print('fileDownload');
      download.connect('decide-destination', Lang.bind(this, this._showInfobar));
      return download.connect('finished', Lang.bind(this, this._hideInfobar));
    },
    _onNewMail: function() {
      var js;
      print('_onNewMail');

      /*
      send shortcut via javascript to webview, that it open a new compose window
       */
      js = "(function() {\n\n//The compose button\nvar composeEl = document.getElementsByClassName('T-I J-J5-Ji T-I-KE L3')[0];\n\nif(composeEl) {\n  //Trigger mouse down event\n  var mouseDown = document.createEvent('MouseEvents');\n  mouseDown.initEvent( 'mousedown', true, false, window, 0, 0, 0, 0, 0, false, false, true, false, 0, null);\n  mouseDown.shiftKey = true;\n  console.log(mouseDown.shiftKey);\n  console.log(mouseDown.metaKey);\n  console.log(mouseDown.altKey);\n  console.log(mouseDown.ctrlKey);\n  composeEl.dispatchEvent(mouseDown);\n\n  //Trigger mouse up event\n  var mouseUp = document.createEvent('MouseEvents');\n  mouseUp.initEvent( 'mouseup', true, false, window, 0, 0, 0, 0, 0, false, false, true, false, 0, null);\n  composeEl.dispatchEvent(mouseUp)\n\n  return true;\n}\nreturn false;\n}).call(this);";
      this._webview.run_javascript(js, null, function() {});
      return this._window.present();
    },
    _showInfobar: function(download, suggested_filename) {
      this._message.set_markup("<b>Downloading: " + suggested_filename + "</b>");
      this._revealer.set_reveal_child(true);
      print('Started download of ' + suggested_filename);
      return false;
    },
    _hideInfobar: function(download) {
      print('hideInfobar');
      return Glib.timeout_add(Glib.PRIORITY_DEFAULT, 2000, Lang.bind(this, function() {
        this._revealer.set_reveal_child(false);
        return false;
      }));
    },
    _onKeyPress: function(widget, event) {}
  });

  app = new Palomino();

  app.application.run(ARGV);

}).call(this);
